/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AnonymousMessagingInterface extends Interface {
    getFunction(nameOrSignature: "messages" | "sendMessage" | "Add" | "ScalarBaseMult" | "HashToEcc" | "usedKeyImages" | "ScalarMult"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MessageSent"): EventFragment;

    encodeFunctionData(functionFragment: 'messages', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sendMessage', values: [string, BigNumberish[], BigNumberish[], [BigNumberish, BigNumberish], BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'Add', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'ScalarBaseMult', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'HashToEcc', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'usedKeyImages', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ScalarMult', values: [BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'messages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'Add', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ScalarBaseMult', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HashToEcc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedKeyImages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ScalarMult', data: BytesLike): Result;
  }

  
    export namespace MessageSentEvent {
      export type InputTuple = [content: string, timestamp: BigNumberish];
      export type OutputTuple = [content: string, timestamp: bigint];
      export interface OutputObject {content: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AnonymousMessaging extends BaseContract {
    
    connect(runner?: ContractRunner | null): AnonymousMessaging;
    waitForDeployment(): Promise<this>;

    interface: AnonymousMessagingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    messages: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {content: string, timestamp: bigint }],
      'view'
    >
    

    
    sendMessage: TypedContractMethod<
      [_content: string, _publicKeysX: BigNumberish[], _publicKeysY: BigNumberish[], _keyImage: [BigNumberish, BigNumberish], _c0: BigNumberish, _s: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    Add: TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, x2: BigNumberish, y2: BigNumberish, ],
      [[bigint, bigint] & {x3: bigint, y3: bigint }],
      'view'
    >
    

    
    ScalarBaseMult: TypedContractMethod<
      [scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >
    

    
    HashToEcc: TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >
    

    
    usedKeyImages: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    ScalarMult: TypedContractMethod<
      [px: BigNumberish, py: BigNumberish, scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'messages'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {content: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'sendMessage'): TypedContractMethod<
      [_content: string, _publicKeysX: BigNumberish[], _publicKeysY: BigNumberish[], _keyImage: [BigNumberish, BigNumberish], _c0: BigNumberish, _s: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'Add'): TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, x2: BigNumberish, y2: BigNumberish, ],
      [[bigint, bigint] & {x3: bigint, y3: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'ScalarBaseMult'): TypedContractMethod<
      [scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'HashToEcc'): TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'usedKeyImages'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'ScalarMult'): TypedContractMethod<
      [px: BigNumberish, py: BigNumberish, scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >;

    getEvent(key: 'MessageSent'): TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;

    filters: {
      
      'MessageSent(string,uint256)': TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
      MessageSent: TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
    
    };
  }