/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Secp256k', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Secp256k__factory>
getContractFactory(name: 'Secp256k', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Secp256k__factory>
getContractFactory(name: 'UntraceableVoting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UntraceableVoting__factory>
getContractFactory(name: 'AnonymousMessaging', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AnonymousMessaging__factory>

  getContractAt(name: 'Secp256k', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Secp256k>
getContractAt(name: 'Secp256k', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Secp256k>
getContractAt(name: 'UntraceableVoting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UntraceableVoting>
getContractAt(name: 'AnonymousMessaging', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AnonymousMessaging>

  deployContract(name: 'Secp256k', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Secp256k>
deployContract(name: 'Secp256k', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Secp256k>
deployContract(name: 'UntraceableVoting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UntraceableVoting>
deployContract(name: 'AnonymousMessaging', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AnonymousMessaging>

  deployContract(name: 'Secp256k', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Secp256k>
deployContract(name: 'Secp256k', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Secp256k>
deployContract(name: 'UntraceableVoting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UntraceableVoting>
deployContract(name: 'AnonymousMessaging', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AnonymousMessaging>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  