/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface UntraceableVotingInterface extends Interface {
    getFunction(nameOrSignature: "createVote" | "updateCurve" | "VoteLeaders" | "oops" | "VoteAnnonymous" | "VoteState" | "votings" | "addVotersToVote" | "CompleteVote"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createVote', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'updateCurve', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'VoteLeaders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'oops', values?: undefined): string;
encodeFunctionData(functionFragment: 'VoteAnnonymous', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'VoteState', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'votings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'addVotersToVote', values: [BigNumberish, BigNumberish[], BigNumberish[], BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'CompleteVote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCurve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VoteLeaders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oops', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VoteAnnonymous', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VoteState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addVotersToVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CompleteVote', data: BytesLike): Result;
  }

  

  export interface UntraceableVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): UntraceableVoting;
    waitForDeployment(): Promise<this>;

    interface: UntraceableVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createVote: TypedContractMethod<
      [id: BigNumberish, candidatesIDs: AddressLike[], ],
      [void],
      'payable'
    >
    

    
    updateCurve: TypedContractMethod<
      [curveDest: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    VoteLeaders: TypedContractMethod<
      [id: BigNumberish, ],
      [[string[], bigint] & {amountOfLeadingCandidates: bigint }],
      'view'
    >
    

    
    oops: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    VoteAnnonymous: TypedContractMethod<
      [id: BigNumberish, candidateId: AddressLike, Ix: BigNumberish, Iy: BigNumberish, c: BigNumberish, s: BigNumberish[], ],
      [void],
      'payable'
    >
    

    
    VoteState: TypedContractMethod<
      [id: BigNumberish, candidate: AddressLike, ],
      [[boolean, bigint]],
      'view'
    >
    

    
    votings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean, boolean] & {creator: string, id: bigint, val: bigint, threashold: bigint, votecounter: bigint, done: boolean, ready: boolean }],
      'view'
    >
    

    
    addVotersToVote: TypedContractMethod<
      [id: BigNumberish, allowedVotersX: BigNumberish[], allowedVotersY: BigNumberish[], threashold: BigNumberish, ready: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    CompleteVote: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createVote'): TypedContractMethod<
      [id: BigNumberish, candidatesIDs: AddressLike[], ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'updateCurve'): TypedContractMethod<
      [curveDest: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'VoteLeaders'): TypedContractMethod<
      [id: BigNumberish, ],
      [[string[], bigint] & {amountOfLeadingCandidates: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'oops'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'VoteAnnonymous'): TypedContractMethod<
      [id: BigNumberish, candidateId: AddressLike, Ix: BigNumberish, Iy: BigNumberish, c: BigNumberish, s: BigNumberish[], ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'VoteState'): TypedContractMethod<
      [id: BigNumberish, candidate: AddressLike, ],
      [[boolean, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'votings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean, boolean] & {creator: string, id: bigint, val: bigint, threashold: bigint, votecounter: bigint, done: boolean, ready: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'addVotersToVote'): TypedContractMethod<
      [id: BigNumberish, allowedVotersX: BigNumberish[], allowedVotersY: BigNumberish[], threashold: BigNumberish, ready: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'CompleteVote'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }