/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface Secp256kInterface extends Interface {
    getFunction(nameOrSignature: "Add" | "ScalarBaseMult" | "HashToEcc" | "ScalarMult"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'Add', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'ScalarBaseMult', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'HashToEcc', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'ScalarMult', values: [BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'Add', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ScalarBaseMult', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HashToEcc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ScalarMult', data: BytesLike): Result;
  }

  

  export interface Secp256k extends BaseContract {
    
    connect(runner?: ContractRunner | null): Secp256k;
    waitForDeployment(): Promise<this>;

    interface: Secp256kInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    Add: TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, x2: BigNumberish, y2: BigNumberish, ],
      [[bigint, bigint] & {x3: bigint, y3: bigint }],
      'view'
    >
    

    
    ScalarBaseMult: TypedContractMethod<
      [scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >
    

    
    HashToEcc: TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >
    

    
    ScalarMult: TypedContractMethod<
      [px: BigNumberish, py: BigNumberish, scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'Add'): TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, x2: BigNumberish, y2: BigNumberish, ],
      [[bigint, bigint] & {x3: bigint, y3: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'ScalarBaseMult'): TypedContractMethod<
      [scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'HashToEcc'): TypedContractMethod<
      [x1: BigNumberish, y1: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'ScalarMult'): TypedContractMethod<
      [px: BigNumberish, py: BigNumberish, scalar: BigNumberish, ],
      [[bigint, bigint] & {qx: bigint, qy: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }