/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { Secp256k, Secp256kInterface } from "../../UntraceableVoting.sol/Secp256k.js";

  const _abi = [
  {
    "constant": true,
    "inputs": [
      {
        "name": "x1",
        "type": "uint256"
      },
      {
        "name": "y1",
        "type": "uint256"
      },
      {
        "name": "x2",
        "type": "uint256"
      },
      {
        "name": "y2",
        "type": "uint256"
      }
    ],
    "name": "Add",
    "outputs": [
      {
        "name": "x3",
        "type": "uint256"
      },
      {
        "name": "y3",
        "type": "uint256"
      }
    ],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [
      {
        "name": "scalar",
        "type": "uint256"
      }
    ],
    "name": "ScalarBaseMult",
    "outputs": [
      {
        "name": "qx",
        "type": "uint256"
      },
      {
        "name": "qy",
        "type": "uint256"
      }
    ],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [
      {
        "name": "x1",
        "type": "uint256"
      },
      {
        "name": "y1",
        "type": "uint256"
      }
    ],
    "name": "HashToEcc",
    "outputs": [
      {
        "name": "qx",
        "type": "uint256"
      },
      {
        "name": "qy",
        "type": "uint256"
      }
    ],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [
      {
        "name": "px",
        "type": "uint256"
      },
      {
        "name": "py",
        "type": "uint256"
      },
      {
        "name": "scalar",
        "type": "uint256"
      }
    ],
    "name": "ScalarMult",
    "outputs": [
      {
        "name": "qx",
        "type": "uint256"
      },
      {
        "name": "qy",
        "type": "uint256"
      }
    ],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class Secp256k__factory {
    static readonly abi = _abi;
    static createInterface(): Secp256kInterface {
      return new Interface(_abi) as Secp256kInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): Secp256k {
      return new Contract(address, _abi, runner) as unknown as Secp256k;
    }
  }
  