// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "poseidon-solidity/PoseidonT3.sol";

contract MerkleTree {
    uint32 public constant TREE_DEPTH = 20;
    uint32 public constant ROOT_HISTORY_SIZE = 30;
    bytes public constant ZERO_VALUE = "21663839004416932945382355908790599225266501822907911457504978515578255421292";

    bytes32[TREE_DEPTH] public filledSubtrees; // for efficiency I'm storing the last left-side hash of each level of the tree
    mapping(uint32 => bytes32) public roots;
    uint32 public nextIndex; /// next leaf slot


    constructor() {
        for (uint32 i = 0; i < TREE_DEPTH; i++) filledSubtrees[i] = _zeros(i);
        roots[0] = _hashLeftRight(
            _zeros(TREE_DEPTH - 1),
            _zeros(TREE_DEPTH - 1)
        );
    }

    function _hashLeftRight(
        bytes32 left, 
        bytes32 right
    ) internal pure returns (bytes32) 
    {
        return bytes32(PoseidonT3.hash([uint256(left), uint256(right)]));
    }

    function _insert(bytes32 leaf) internal returns (uint32 insertedIndex) {
        uint32 currentIndex = nextIndex;
        require(
            currentIndex < uint32(2)**TREE_DEPTH, 
            "Merkle tree full"
        );

        bytes32 currentLevelHash = leaf;
        for (uint32 i = 0; i < TREE_DEPTH; i++) {
            if (currentIndex % 2 == 0) {
                filledSubtrees[i] = currentLevelHash;
                currentLevelHash = _hashLeftRight(currentLevelHash, _zeros(i));
            } else {
                currentLevelHash = _hashLeftRight(filledSubtrees[i], currentLevelHash);
            }
            currentIndex /= 2;
        }

        uint32 newRootIndex = (nextIndex + 1) % ROOT_HISTORY_SIZE;
        roots[newRootIndex] = currentLevelHash;
        nextIndex++;
        return nextIndex - 1;
    }

    function getLastRoot() public view returns (bytes32) {
        return roots[nextIndex % ROOT_HISTORY_SIZE];
    }

    function isKnownRoot(bytes32 root) public view returns (bool) {
        if (root == bytes32(0)) return false;
        
        uint32 i = nextIndex % ROOT_HISTORY_SIZE;
        for (uint32 step = 0; step < ROOT_HISTORY_SIZE; step++) {
            if (roots[i] == root) return true;
            
            if (i == 0) i = ROOT_HISTORY_SIZE - 1;
            else i--;
        }

        return false;
    }

    /// I have precomputed Poseidon hash of an all zero subtrees (generated by script in scripts/computeZeros.js)
    function _zeros(uint256 level) internal pure returns (bytes32) {
        if (level == 0)  return bytes32(uint256(0x2fe54c60d3acabf3343a35b6eba15db4821b340f76e741e2249685ed4899af6c));
        if (level == 1)  return bytes32(uint256(0x13e37f2d6cb86c78ccc1788607c2b199788c6bb0a615a21f2e7a8e88384222f8));
        if (level == 2)  return bytes32(uint256(0x217126fa352c326896e8c2803eec8fd63ad50cf65edfef27a41a9e32dc622765));
        if (level == 3)  return bytes32(uint256(0x0e28a61a9b3e91007d5a9e3ada18e1b24d6d230c618388ee5df34cacd7397eee));
        if (level == 4)  return bytes32(uint256(0x27953447a6979839536badc5425ed15fadb0e292e9bc36f92f0aa5cfa5013587));
        if (level == 5)  return bytes32(uint256(0x194191edbfb91d10f6a7afd315f33095410c7801c47175c2df6dc2cce0e3affc));
        if (level == 6)  return bytes32(uint256(0x1733dece17d71190516dbaf1927936fa643dc7079fc0cc731de9d6845a47741f));
        if (level == 7)  return bytes32(uint256(0x267855a7dc75db39d81d17f95d0a7aa572bf5ae19f4db0e84221d2b2ef999219));
        if (level == 8)  return bytes32(uint256(0x1184e11836b4c36ad8238a340ecc0985eeba665327e33e9b0e3641027c27620d));
        if (level == 9)  return bytes32(uint256(0x0702ab83a135d7f55350ab1bfaa90babd8fc1d2b3e6a7215381a7b2213d6c5ce));
        if (level == 10) return bytes32(uint256(0x2eecc0de814cfd8c57ce882babb2e30d1da56621aef7a47f3291cffeaec26ad7));
        if (level == 11) return bytes32(uint256(0x280bc02145c155d5833585b6c7b08501055157dd30ce005319621dc462d33b47));
        if (level == 12) return bytes32(uint256(0x045132221d1fa0a7f4aed8acd2cbec1e2189b7732ccb2ec272b9c60f0d5afc5b));
        if (level == 13) return bytes32(uint256(0x27f427ccbf58a44b1270abbe4eda6ba53bd6ac4d88cf1e00a13c4371ce71d366));
        if (level == 14) return bytes32(uint256(0x1617eaae5064f26e8f8a6493ae92bfded7fde71b65df1ca6d5dcec0df70b2cef));
        if (level == 15) return bytes32(uint256(0x20c6b400d0ea1b15435703c31c31ee63ad7ba5c8da66cec2796feacea575abca));
        if (level == 16) return bytes32(uint256(0x09589ddb438723f53a8e57bdada7c5f8ed67e8fece3889a73618732965645eec));
        if (level == 17) return bytes32(uint256(0x0064b6a738a5ff537db7b220f3394f0ecbd35bfd355c5425dc1166bf3236079b));
        if (level == 18) return bytes32(uint256(0x095de56281b1d5055e897c3574ff790d5ee81dbc5df784ad2d67795e557c9e9f));
        if (level == 19) return bytes32(uint256(0x11cf2e2887aa21963a6ec14289183efe4d4c60f14ecd3d6fe0beebdf855a9b63));
        revert("MerkleTree: invalid level");
    }
}
