/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DynamicConsentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkConsent"
      | "getConsent"
      | "giveConsent"
      | "revokeConsent"
      | "updateConsent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConsentGiven" | "ConsentRevoked" | "ConsentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkConsent",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsent",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "giveConsent",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateConsent",
    values: [AddressLike, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConsent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "giveConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConsent",
    data: BytesLike
  ): Result;
}

export namespace ConsentGivenEvent {
  export type InputTuple = [
    patient: AddressLike,
    provider: AddressLike,
    purpose: string,
    dataType: string
  ];
  export type OutputTuple = [
    patient: string,
    provider: string,
    purpose: string,
    dataType: string
  ];
  export interface OutputObject {
    patient: string;
    provider: string;
    purpose: string;
    dataType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [patient: AddressLike, provider: AddressLike];
  export type OutputTuple = [patient: string, provider: string];
  export interface OutputObject {
    patient: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentUpdatedEvent {
  export type InputTuple = [
    patient: AddressLike,
    provider: AddressLike,
    newPurpose: string,
    newDataType: string
  ];
  export type OutputTuple = [
    patient: string,
    provider: string,
    newPurpose: string,
    newDataType: string
  ];
  export interface OutputObject {
    patient: string;
    provider: string;
    newPurpose: string;
    newDataType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DynamicConsent extends BaseContract {
  connect(runner?: ContractRunner | null): DynamicConsent;
  waitForDeployment(): Promise<this>;

  interface: DynamicConsentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkConsent: TypedContractMethod<
    [patient: AddressLike, provider: AddressLike],
    [boolean],
    "view"
  >;

  getConsent: TypedContractMethod<
    [patient: AddressLike, provider: AddressLike],
    [
      [boolean, string, string, bigint] & {
        isActive: boolean;
        purpose: string;
        dataType: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  giveConsent: TypedContractMethod<
    [provider: AddressLike, purpose: string, dataType: string],
    [void],
    "nonpayable"
  >;

  revokeConsent: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  updateConsent: TypedContractMethod<
    [provider: AddressLike, newPurpose: string, newDataType: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkConsent"
  ): TypedContractMethod<
    [patient: AddressLike, provider: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConsent"
  ): TypedContractMethod<
    [patient: AddressLike, provider: AddressLike],
    [
      [boolean, string, string, bigint] & {
        isActive: boolean;
        purpose: string;
        dataType: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "giveConsent"
  ): TypedContractMethod<
    [provider: AddressLike, purpose: string, dataType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateConsent"
  ): TypedContractMethod<
    [provider: AddressLike, newPurpose: string, newDataType: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConsentGiven"
  ): TypedContractEvent<
    ConsentGivenEvent.InputTuple,
    ConsentGivenEvent.OutputTuple,
    ConsentGivenEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentUpdated"
  ): TypedContractEvent<
    ConsentUpdatedEvent.InputTuple,
    ConsentUpdatedEvent.OutputTuple,
    ConsentUpdatedEvent.OutputObject
  >;

  filters: {
    "ConsentGiven(address,address,string,string)": TypedContractEvent<
      ConsentGivenEvent.InputTuple,
      ConsentGivenEvent.OutputTuple,
      ConsentGivenEvent.OutputObject
    >;
    ConsentGiven: TypedContractEvent<
      ConsentGivenEvent.InputTuple,
      ConsentGivenEvent.OutputTuple,
      ConsentGivenEvent.OutputObject
    >;

    "ConsentRevoked(address,address)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;

    "ConsentUpdated(address,address,string,string)": TypedContractEvent<
      ConsentUpdatedEvent.InputTuple,
      ConsentUpdatedEvent.OutputTuple,
      ConsentUpdatedEvent.OutputObject
    >;
    ConsentUpdated: TypedContractEvent<
      ConsentUpdatedEvent.InputTuple,
      ConsentUpdatedEvent.OutputTuple,
      ConsentUpdatedEvent.OutputObject
    >;
  };
}
