/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DynamicConsent } from "./DynamicConsent";
export * as factories from "./factories";
export { DynamicConsent__factory } from "./factories/DynamicConsent__factory";
